language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm install
  - npm deploy
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  keep_history: true
  on:
    branch: master