language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm install
deploy:
  provider: script
  script: npm run build; push-dir --dir=dist --branch=gh-pages --cleanup
  github_token: $token 
  on:
    branch: master