language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm install
# deploy:
#   provider: pages
#   local_dir: dist
#   skip_cleanup: true
#   github_token: $token 
#   keep_history: true
#   on:
#     branch: master

    deploy:
  provider: script
  script: npm deploy
  github_token: $token 
  on:
    branch: gh-pages