language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm install
  - npm deploy
deploy:
 "npm run build; push-dir --dir=dist --branch=gh-pages --cleanup"
  # provider: pages
  # local_dir: dist
  # skip_cleanup: true
  github_token: $token 
  # keep_history: true
  # on:
  #   branch: master