language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm install
  - eslint --ext .js,.vue src
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $token 
  keep_history: true
  on:
    branch: master
after_success:
  - npm run deploy